### ISSUE TITLE
Mapa mental de la comunicación Oral y Escrita

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Ariadnamonserrat10#1]
Hecho por: Ariadna Monserrat Lòpez Aparicio 1BS
![Comunicación Oral y Escrita](https://user-images.githubusercontent.com/112223282/190904272-563ddd79-7c42-4ce4-b072-2079fa04a07a.png)

**Comment by ErikCuevas03** [comment]
19 
bien hecho!

**Comment by josealfredo79** [comment]
Bien hecho y revisado
